log:
  dateFormat: "YYYY-MM-DD"
  datetimeFormat: "YYYY-MM-DD HH:mm:ss"
  jsonIndent: 2
cache:
  ttl: 300
  checkPeriod: 600
  useClones: false
express:
  requestSizeLimit: 50mb
spotify:
  apiUrl: "https://api.spotify.com/v1"
  endpoints:
    topArtists: "/me/top/artists"
    topTracks: "/me/top/tracks"
